services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    restart: always
    environment:
      - POSTGRES_DB=vector_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: